trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        echo '$(System.DefaultWorkingDirectory)'
        echo ${{ variables.location }}
        echo ${{ variables.AllowedIPs }}
        terraform --version
        terraform -chdir=deployments/centralus-3nic init
        terraform -chdir=deployments/centralus-3nic plan -out=tfplan 
      displayName: 'Terraform Init and Plan'
