trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: tfvars

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        echo '$(System.DefaultWorkingDirectory)'
        echo $(location)
        echo $(AllowedIPs)
        echo $(f5_ssh_publickey)
        echo $(testvar)
        terraform --version
        terraform -chdir=deployments/centralus-3nic init
        terraform -chdir=deployments/centralus-3nic plan -var "location=$(location)" -var "AllowedIPs=$(AllowedIPs)" -var "f5_ssh_publickey=$(f5_ssh_publickey)" -out=tfplan
      displayName: 'Terraform Init and Plan'
